### ISSUE TITLE
Añadir redes sociales a la barra de título

### ISSUE THREAD

**Issue by alexfernandez** [javascript-beer/javascript-beer.github.io#2]
* [Twitter](https://twitter.com/JavascriptBeer)
* [YouTube](https://www.youtube.com/channel/UCo4rtqAgSMCEzw7ibyHF6YA)
* [LinkedIn](https://www.linkedin.com/company/75870724/)

¿Alguna más, @Pand-o-Ra ?

**Comment by alexfernandez** [comment]
El link de Twitter estaba mal, llevaba a https://javascript.beer/twitter.com/javascriptBeer. Lo arreglo en el commit b7ca869.

**Comment by Pand-o-Ra** [comment]
Añadiría tb IG cd Álvaro la cree...

**Comment by alexfernandez** [comment]
@felixzapata No consigo subir la versión "arreglada" con las instrucciones del `README.md` :thinking:  ¿Me ayudas, plis?

**Comment by alexfernandez** [comment]
Por ahora ya está todo arreglado. @Pand-o-Ra Please crea otro issue cuando tengamos Instagram, vale?
